:backends:
    - 'trocla'
    - 'yaml'
:hierarchy:
    - "nodes/%{::clientcert}"
    - "roles/%{::role}"
    - 'defaults'
:yaml:
    :datadir: 'spec/config/hieradata'
:trocla:
    :config: 'spec/config/troclarc.yaml'
:logger: 'noop'
